function H = fKin(q,lamda)
%FKIN
%    H = FKIN(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Jun-2017 15:07:15
 if iscolumn(q)
      q = q';
 end
 

q1=q(1,1);
q2=q(1,2);
q3=q(1,3);
q4=q(1,4);
q5=q(1,5);
q6=q(1,6);


t2 = cos(q6);
t3 = sin(q2);
t4 = cos(q2);
t5 = sin(q4);
t6 = sin(q6);
t7 = cos(q4);
t8 = q5+lamda*5.535e-2;
H = reshape([-t3.*t6-t2.*t4.*t5,t2.*t7,-t4.*t6+t2.*t3.*t5,0.0,-t2.*t3+t4.*t5.*t6,-t6.*t7,-t2.*t4-t3.*t5.*t6,0.0,-t4.*t7,-t5,t3.*t7,0.0,t3.*(1.3e1./4.0e2)+t4.*1.33e-3-t4.*t5.*4.05e-2-t4.*t7.*t8,q3+t7.*4.05e-2-t5.*t8+2.1e1./5.0e2,q1-t3.*1.33e-3+t4.*(1.3e1./4.0e2)+t3.*t5.*4.05e-2+t3.*t7.*t8+1.1e1./5.0e2,1.0],[4,4]);
