function J = j_Extended(q,Ltool,lamda)
%J_EXTENDED
%    J = J_EXTENDED(q,Ltool,lamda)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Jul-2017 18:04:17
%LTOOL = length of tool
q0=q(1,1);
q1=q(1,2);
q2=q(1,3);
q3=q(1,4);
q4=q(1,5);
q5=q(1,6);

t2 = sin(q2);
t3 = cos(q4);
t4 = t2.*t3.*5.535e-2;
t5 = cos(q2);
t6 = sin(q4);
t7 = t3.*t5.*5.535e-2;
t8 = t6.*1.107e3;
t9 = q5.*t6.*2.0e4;
t10 = t3.*-8.1e2+t8+t9;
J = reshape([0.0,0.0,1.0,0.0,0.0,0.0,t4+t5.*(1.3e1./4.0e2)-lamda.*(t4-Ltool.*t2.*t3)+t2.*t6.*4.05e-2+q5.*t2.*t3,0.0,t2.*(-1.3e1./4.0e2)+t7-lamda.*(t7-Ltool.*t3.*t5)+t5.*t6.*4.05e-2+q5.*t3.*t5,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t5.*t10.*5.0e-5,t3.*(-5.535e-2)-t6.*4.05e-2-q5.*t3,t2.*t10.*(-5.0e-5),t2,0.0,t5,-t3.*t5,-t6,t2.*t3,0.0,0.0,0.0],[6,5]);
