function J = j_Extend(q,lambda)
%J_EXTEND

%    J = J_EXTEND(LAMBDA,Q2,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Jun-2017 16:55:03
if iscolumn(q)
      q = q';
 end
 

q1=q(1,1);
q2=q(1,2);
q3=q(1,3);
q4=q(1,4);
q5=q(1,5);
q6=q(1,6);

t2 = sin(q2);
t3 = cos(q2);
t4 = cos(q4);
t5 = sin(q4);
t6 = q5+5.535e-2;
t7 = t3.*(1.3e1./4.0e2);
t8 = t2.*t5.*4.05e-2;
t9 = t2.*t4.*t6;
J = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,t2.*(-1.33e-3)+t7+t8+t9,0.0,1.0,0.0,t2.*(-1.33e-3)+t7+t8+lambda.*t2.*t4.*t6,0.0,t2.*(-1.3e1./4.0e2)-t3.*1.33e-3+t3.*t5.*4.05e-2+lambda.*t3.*t4.*t6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,t3.*t4.*(-4.05e-2)+t3.*t5.*t6,t2,0.0,t3,t3.*t4.*(-4.05e-2)+lambda.*t3.*t5.*t6,t5.*(-4.05e-2)-lambda.*t4.*t6,t2.*t4.*4.05e-2-lambda.*t2.*t5.*t6,-t3.*t4,0.0,0.0,0.0,-lambda.*t3.*t4,-lambda.*t5,lambda.*t2.*t4,0.0,-t3.*t4,-t5,t2.*t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*t4.*t6,-t5.*t6,t9],[7,7]);
