function Jtool = j_Tool(q, Ltool)
%J_TOOL
%    JTOOL = J_TOOL(q,Ltool,lamda)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Jul-2017 18:04:17
q0=q(1,1);
q1=q(1,2);
q2=q(1,3);
q3=q(1,4);
q4=q(1,5);
q5=q(1,6);

t2 = sin(q2);
t3 = cos(q4);
t4 = cos(q2);
t5 = sin(q4);
t6 = t5.*1.107e3;
t7 = q5.*t5.*2.0e4;
t8 = t3.*-8.1e2+t6+t7;
Jtool = reshape([0.0,0.0,1.0,0.0,0.0,0.0,t4.*(1.3e1./4.0e2)+t2.*t5.*4.05e-2+Ltool.*t2.*t3+q5.*t2.*t3,0.0,t2.*(-1.3e1./4.0e2)+t4.*t5.*4.05e-2+Ltool.*t3.*t4+q5.*t3.*t4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t4.*t8.*5.0e-5,t3.*(-5.535e-2)-t5.*4.05e-2-q5.*t3,t2.*t8.*(-5.0e-5),t2,0.0,t4,-t3.*t4,-t5,t2.*t3,0.0,0.0,0.0],[6,5]);
